### ISSUE TITLE
Can't run the bot

### ISSUE THREAD

**Issue by bchurton** [LuisMayo/ace-attorney-discord-bot#52]
Doing `python main.py`:
```py
  File "main.py", line 59
    print(f"The mapping key {keyErrorException} is missing in the config file (config.yaml)!")
                                                                                            ^
SyntaxError: invalid syntax
```

Doing `python3 main.py`:
```py
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from message import Message
  File "/root/ace-attorney/message.py", line 5, in <module>
    from objection_engine.beans.comment import Comment
  File "/usr/local/lib/python3.8/dist-packages/objection_engine/__init__.py", line 2, in <module>
    from .renderer import render_comment_list
  File "/usr/local/lib/python3.8/dist-packages/objection_engine/renderer.py", line 7, in <module>
    from . import anim
  File "/usr/local/lib/python3.8/dist-packages/objection_engine/anim.py", line 3, in <module>
    from objection_engine.parse_tags import get_rich_boxes
  File "/usr/local/lib/python3.8/dist-packages/objection_engine/parse_tags.py", line 5, in <module>
    from objection_engine.beans.font_tools import get_best_font, split_str_into_newlines, split_with_joined_sentences
  File "/usr/local/lib/python3.8/dist-packages/objection_engine/beans/font_tools.py", line 51, in <module>
    def fit_words_within_width(words: Union[list[str], str], font: ImageFont.FreeTypeFont, insert_space: bool):
TypeError: 'type' object is not subscriptable
```

**Comment by bchurton** [comment]
Fixed with an upgrade to python 3.9
